environment:
  matrix:
    - nodejs_version: 10
      platform: x64
    - nodejs_version: 10
      platform: x86

os: Visual Studio 2015

install:
  - scripts\build-appveyor.bat

build: OFF
test: OFF
deploy: OFF
